DROP TABLE IF EXISTS Farm CASCADE;
CREATE TABLE Farm (
	id BIGINT AUTO_INCREMENT NOT NULL,
	farm_name VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	telephone BIGINT NOT NULL,
	PRIMARY KEY (id)
	);